---
spring:
  datasource:
    url: jdbc:h2:~/data/cat-toys
    jpa:
      hibernate:
        ddl-auto: update

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

---
jwt:
  secret: "12345678901234567890123456789012"
